#define RED     "\033[31m"
#define GREEN   "\033[32m"
#define YELLOW  "\033[33m"
#define BLUE    "\033[34m"
#define MAGENTA "\033[35m"
#define CYAN    "\033[36m"
#define GRAY    "\033[38;5;243m"
#define BOLD    "\033[1m"
#define RESET   "\033[0m"

#define COLOR_TYPE       CYAN
#define COLOR_FILENAME   RESET
#define COLOR_OCTAL      RESET
#define COLOR_READ       YELLOW
#define COLOR_WRITE      RED
#define COLOR_EXECUTE    GREEN
#define COLOR_SPECIAL    MAGENTA
#define COLOR_DIRECTORY  CYAN
#define COLOR_LINK       MAGENTA
#define COLOR_GRAYED_OUT GRAY
