.Dd October 29, 2025
.Dt PERMINFO 1
.Os
.Sh NAME
.Nm perminfo
.Nd Display permission information
.Sh SYNOPSIS
.Nm perminfo
.Op Fl hlv
.Op Ar file ...
.Sh DESCRIPTION
.Nm
is simple tool for displaying file permissions written in C.
If no files are given, the permissions of the current directory are displayed.
.Pp
Supported options:
.Bl -tag -width Ds
.It Fl h , Fl Fl help
Display help message
.It Fl l , Fl Fl follow-links
Follow symbolic links
.It Fl v , Fl Fl version
Display version information
.El
