name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '*.png'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Build perminfo
        run: make
